### ISSUE TITLE
Welke Licence gaan we gebruiken?

### ISSUE THREAD

**Issue by KaoriYes** [KaoriYes/studs#1]
# Licence voorkeur?
Ik heb hier zelf niet een voorkeur voor. Hebben jullie er eentje waar je voorstander van bent?

Ik had in A1 ```GNU licence``` gebruikt.

**Comment by h1bba** [comment]
Hoi Quinten,

Via choosealicense.com heb ik even onderzocht welke license voor ons het handigst zou zijn.

![image](https://user-images.githubusercontent.com/60386159/226371067-2256aeef-a0a2-4c33-a3dd-5a88385de03d.png)

**MIT**

Ik heb een pull request gemaakt om deze license te recommenden.
