### ISSUE TITLE
Individuele feature af, MET Styling 

### ISSUE THREAD

**Issue by KaoriYes** [KaoriYes/studs#6]
Voor maandag wil ik een hoop gedaan hebben.
**Het moet namelijk woensdag avond af** 
Dus: Ik wil dat iedereen hun feature werkend is, _MET STYLING_ (ongeveer zoals Ali heeft gedesignd). 
Daarnaast is het handig als de wiki van elke feature bijgewerkt is en individuele wiki pagina's af zijn.
Verder wil ik Maandag alles mergen, dus ik wil ook dat iedereen aanwezig is op school. Dan kunnen we er samen even snel doorheen gaan en alle fouten gelijk fixen. We hebben dan nog twee dagen om alle fouten en problemen te fixen. Ik stel voor om maandag: om 10.30 op school te zijn. Dan hebben we de hele dag.

**Comment by h1bba** [comment]
Hey Quinten, ik close deze issue omdat de features af zijn
